[package]
name = "clickbench-infino"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "clickbench-infino"
path = "src/main.rs"

[dependencies]
infino = "0.1.2"
arrow = "59"
arrow-array = "59"
arrow-schema = "59"
parquet = "59"
glob = "0.3"

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
